services:
  nginx:
    container_name: nginx
    image: focela/nginx:1.24
    restart: always
    networks:
      - focela-network
    depends_on:
      - php-fpm
      - mysql
    ports:
      - ${NGINX_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443
    volumes: &shared-volumes
      - ./docker/nginx/sites-enabled:/etc/nginx/conf.d
      - ./src:/var/www
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - sock-data:/sock
      - ssl-data:/etc/nginx/certs
    extra_hosts: &extra-hosts
      - "*:172.17.0.1"

  php-fpm:
    container_name: php-fpm
    image: focela/php:8.4
    restart: always
    networks:
      - focela-network
    volumes: *shared-volumes
    extra_hosts: *extra-hosts
    environment:
      BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
      BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
      COMPOSER_DISABLE_XDEBUG_WARN: ${COMPOSER_DISABLE_XDEBUG_WARN:-1}
      PHP_CS_FIXER_IGNORE_ENV: ${PHP_CS_FIXER_IGNORE_ENV:-1}
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: ${PUPPETEER_SKIP_CHROMIUM_DOWNLOAD:-true}

  mysql:
    container_name: mysql
    image: mysql:8.4
    restart: always
    networks:
      - focela-network
    ports:
      - ${MYSQL_DB_PORT:-3306}:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci"
    ]

volumes:
  nginx-data:
  sock-data:
  ssl-data:
  mysql-data:

networks:
  focela-network:
    driver: bridge
    name: focela-network
