name: Build and Release PHP 8.2

on:
  workflow_dispatch:
  push:
    paths:
      - 'images/php/8.2/**'
      - 'images/php/shared-configs/**'

jobs:
  build-php-82:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_TOKEN }}

      - name: Build and Push PHP 8.2 Image
        uses: docker/build-push-action@v6
        with:
          context: images/php
          file: images/php/8.2/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_PHP_IMAGE }}:8.2
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify Image Push
        run: |
          docker manifest inspect ${{ secrets.DOCKER_PHP_IMAGE }}:8.2
