name: Build and Release PHP 8.1

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'images/php/8.1/**'

jobs:
  build-php-81:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          use: true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_TOKEN }}

      - name: Build and push PHP 8.1 image
        uses: docker/build-push-action@v6
        with:
          context: images/php/8.1
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8
          push: true
          tags: ${{ secrets.DOCKER_PHP_IMAGE }}:8.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
